const dotenv = require('dotenv');
dotenv.config();
const model = require('./models/models');
const swaggerAutogen = require('swagger-autogen')();

const outputFile = './src/swagger/swagger_output.json';
const endpointsFiles = [
    // /lib controllers
];

/* == Version info
    +---------------+---------+------------------+---------+
    | Code status   |  Stage  |      Rule        | Example |
    |               |         |                  | Version |
    +---------------+---------+------------------+---------+
    |     First     |   New   | Start with 1.0.0 |  1.0.0  |
    |    release    | product |                  |         |
    +---------------+---------+------------------+---------+
    |   Backward    |  Patch  |  Increment the   |         |
    |  compatible   | release |   third digit    |  1.0.1  |
    |   bug fixes   |         |                  |         |
    +---------------+---------+------------------+---------+
    |    Backward   |         |  Increment the   |         |
    |   compatible  |  Minor  |   middle digit   |         |
    |      new      | release |  and reset the   |  1.1.0  |
    |    features   |         | last digit to 0  |         |
    +---------------+---------+------------------+---------+
    | Changes that  |         |  Increment the   |         |
    |     break     |  Major  |  first digit and |         |
    |   backward    | release | reset the middle |  2.0.0  |
    | compatibility |         | last digit to 0  |         |
    +---------------+---------+------------------+---------+
*/

const doc = {
    info: {
        version: '1.0.0',
        title: `${process.env.PROJECT_NAME} Generator API`,
        description: 'Documentation automatically generated by the <b>swagger.autogen</b> module.',
    },
    host: `localhost:${process.env.LISTEN_PORT || process.env.PORT}`,
    basePath: '/api/v1/',
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            name: `${process.env.PROJECT_NAME}`,
            description: 'Endpoints',
        },
    ],
    definitions: {
        // MODELS
    },
};

swaggerAutogen(outputFile, endpointsFiles, doc);
