CREATE TABLE `user` (
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
google_user_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    avatar VARCHAR(255) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);



CREATE TABLE cup (
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    year int(4) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);



CREATE TABLE team (
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    avatar VARCHAR(255) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);



CREATE TABLE `match` (
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    cup_id int UNSIGNED NOT NULL,
    team_a_id int UNSIGNED NOT NULL,
    team_b_id int UNSIGNED NOT NULL,
    score_a int DEFAULT NULL,
    score_b int DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (cup_id) REFERENCES cup(id),
    FOREIGN KEY (team_a_id) REFERENCES team(id),
    FOREIGN KEY (team_b_id) REFERENCES team(id)
);



CREATE TABLE bet (
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id int UNSIGNED NOT NULL,
    match_id int UNSIGNED NOT NULL,
score_a int DEFAULT NULL,
score_b int DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES `user`(id),
    FOREIGN KEY (match_id) REFERENCES `match`(id)
);
